### ISSUE TITLE
Current status and support for ubuntu (trusty and/or vivid)

### ISSUE THREAD

**Issue by gerdklingler** [Mayeu/ansible-playbook-rabbitmq#47]
What is the current status about support for ubuntu/trusty and/or ubuntu/vivid.
What are the reason considering the master branch instable?

**Comment by Mayeu** [comment]
Hello,

> What is the current status about support for ubuntu/trusty and/or ubuntu/vivid.
I personally don't manage any Ubuntu > 12.04, and since I did not have any feedback on someone using it in other Ubuntus I can't say it will work. But there is generally only slight differences between Ubuntus, and since the playbook install the RabbitMQ directly from the developer repository it should be OK :)

If you try it in other Ubuntu than 12.04, and it worked, don't hesitate to modify the supported system on the readme, and ideally, please add the associated vagrant VM in the test :)

> What are the reason considering the master branch instable?
Since I merge features from PR that I don't use myself, I prefer to consider the tag stable, and that people that uses the feature can test & use it by selecting master. After some time I end-up tagging master if there no issue raised with the current master modification.

**Comment by williamhogman** [comment]
I just tried it on 14.04. It worked just fine, not a single issue.

**Comment by Mayeu** [comment]
Closing as no other issue report on those OS
